### ISSUE TITLE
Does it work with Leaflet to use its toGeoJSON() function?

### ISSUE THREAD

**Issue by Aaron-Zhao** [jieter/Leaflet-semicircle#10]
Does it work with Leaflet to use its toGeoJSON() function?

It looks like toGeoJSON() just exports a point rather than a polygon type.

**Comment by jieter** [comment]
GeoJSON doesn't support circles. In theory, we could export a polygon approximating the (semi-)circle, but what precision should be used?

It's not straightforward enough to implement in this simple plugin.
