### ISSUE TITLE
circleMarker throwing errors

### ISSUE THREAD

**Issue by cgalvarino** [jieter/Leaflet-semicircle#16]
It appears that #8 has reared its head again.

If I take your circlemarker.html example and change the L.circleMarker line to read
```
L.circleMarker([50.61, -0.0]).setDirection(0, 0).addTo(map);
```
our old friend setDirection not defined is thrown.

I'm @ leaflet 1.0.3.

Many thanks.

**Comment by jieter** [comment]
released leaflet-semicircle@2.0.0, should fix this.
