### ISSUE TITLE
Object doesn't support property or method 'isSemicircle'

### ISSUE THREAD

**Issue by ivleth** [jieter/Leaflet-semicircle#20]
Hi, Semicircle is broken by using leaflet 1.1.0 (http://cdn.leafletjs.com/leaflet/v1.1.0/leaflet-src.js)
See your test page semicircle.html

Error: Object doesn't support property or method 'isSemicircle'
Semicircle.js (125,13)

  L.SVG.include({
        _updateCircle: function (layer) {
            // If we want a circle, we use the original function
            **if (!layer.isSemicircle()) {**
                return _updateCircleSVG.call(this, layer);
            } ... etc etc

**Comment by jieter** [comment]
Thanks for reporting. Are you able to create a PR fixing this?

**Comment by ivleth** [comment]
Hi, I tried but I didn't get it fixed. Something is breaking in 1.1.0 compared 1.0.2

**Comment by jieter** [comment]
Does this help? https://github.com/jieter/Leaflet-semicircle/pull/17

**Comment by ivleth** [comment]
unfortunately it doesn't, same error...

**Comment by jieter** [comment]
should be fixed by fdb647e, released leaflet-semicircle@2.0.0
