### ISSUE TITLE
Layer type checking in Canvas renderer

### ISSUE THREAD

**Issue by lubrige** [jieter/Leaflet-semicircle#24]
It seems that `instanceof SemiCircle` checking for the layer in `_updateCircle` function of SVG renderer, added in fix fdb647e2f7672cb53a247f7e09fc1e1f928355e7, should also be applied to Canvas renderer.

Otherwise, the same error as reported in #20 will occur when drawing `L.circle` using Canvas.

**Comment by jieter** [comment]
@lubrige looks like you are right, are you able to make a pull request?

**Comment by lubrige** [comment]
I've made one. Thank you.
