### ISSUE TITLE
Make plugin available through Bower

### ISSUE THREAD

**Issue by danimt** [jieter/Leaflet-semicircle#3]
Is it possible to register leaflet-semicircle as a bower component?

http://bower.io/#registering-packages

Thanks

**Comment by jieter** [comment]
Hmm, since this is the only request I got and I'm not familiar with Bower, I'm going to say no...

**Comment by krishnaparachikapu** [comment]
Could you please make this available as bower component. 

Thanks,
Krishna

**Comment by jieter** [comment]
@danimt I finally did it anyway...
