### ISSUE TITLE
Can we draw part of the semicircle??

### ISSUE THREAD

**Issue by sonerss** [jieter/Leaflet-semicircle#33]
Hi, Can we draw part of the semicircle which like I show in attachment picture?
![part_of_semicircle](https://user-images.githubusercontent.com/33938115/68021171-bbb31f00-fcb1-11e9-9fe0-97d90f5cffe1.jpg)

**Comment by nikhil-bacancy** [comment]
any updates in this feature ?

**Comment by jieter** [comment]
You would have to adjust the implementation to suit your needs, not something leaflet-semicircle is going to support.
