### ISSUE TITLE
semicirlce and circle is not the same center

### ISSUE THREAD

**Issue by yangbinlovegis** [jieter/Leaflet-semicircle#39]
I use L.circle create circle ,and I L.semicircle ,the center is same latlng , but on the map ,they are diffrent position ,why

**Comment by yangbinlovegis** [comment]
the circle latlng is right ,the semicircle latlng is wrong

**Comment by Severino** [comment]
I experienced the semi-circle becoming a little bit eliptical when using a floating-point number as radius. Which makes the semicircle appear to be not in center. Maybe this is related #40

**Comment by jieter** [comment]
#40 is merged, please re-test.
