### ISSUE TITLE
Precision with concentric semi-circle

### ISSUE THREAD

**Issue by laurentClave** [jieter/Leaflet-semicircle#4]
I have concentric semi-circles with the same radius that do not appear in the same position with different zoom

ZOOM 2 : The circles do not have the same center
![1](https://cloud.githubusercontent.com/assets/7510673/5678076/d4dd0d42-97ee-11e4-8ecb-a273eeedf127.jpg)

ZOOM 1 : The circles are concentric
![2](https://cloud.githubusercontent.com/assets/7510673/5678078/d848d6e6-97ee-11e4-9871-c33055ccfa6f.jpg)

**Comment by jieter** [comment]
Please post an example of the code to produce this error.

**Comment by laurentClave** [comment]
Hi,

OK, i reproduce the bug :
http://jsfiddle.net/fJFWN/123/

In my project the bug is even more visible.

Zoom 3, ok :
![1](https://cloud.githubusercontent.com/assets/7510673/5680480/24e02ba2-980e-11e4-9a21-93c35b5fafdd.jpg)

Zoom 1, bug :
![2](https://cloud.githubusercontent.com/assets/7510673/5680494/3d072f14-980e-11e4-8185-67cb154b5e46.jpg)

Thank

**Comment by laurentClave** [comment]
If the circles have the same angle, it looks like there is no bug

**Comment by laurentClave** [comment]
Up ?

**Comment by laurentClave** [comment]
You don't have a idea of problem ?

**Comment by jieter** [comment]
I had a quick look into it but could not find a solution. Currently lacking the time to dig in deeper, if you can do that, I'll be more than happy to merge your PR.

**Comment by jieter** [comment]
It was a matter of removing the rounding, this looks almost perfect now: 

http://jieter.github.io/Leaflet-semicircle/examples/concentric.html
