### ISSUE TITLE
Demo not working anymore?

### ISSUE THREAD

**Issue by valerio-bozzolan** [jieter/Leaflet-semicircle#41]
Hi! I've clicked on the demo link in the [Leaflet-semicircle README](https://github.com/jieter/Leaflet-semicircle#example) but it's not working anymore. Are you aware of that?

I was just interested in add an operational demo link from this page:

https://leafletjs.com/plugins.html

Thank you so much for your work on this plugin! :)

**Comment by jieter** [comment]
@valerio-bozzolan thanks for the report, should be fixed now.
