### ISSUE TITLE
Not really robust yet for cases when startAngle is bigger than stopAngle.

### ISSUE THREAD

**Issue by inclanfunk** [jieter/Leaflet-semicircle#6]
Do you have a starting point on how this issue could be solved?
In general terms, then I will try to fix it. Thanks

**Comment by jieter** [comment]
Hmm, totally missed this, are you still willing to try to fix it @inclanfunk ?

**Comment by jieter** [comment]
@inclanfunk should be fixed with e098e8ea855321c20f562ebefb2bbc1b757701ba
